rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
script: "bundle exec rake"

matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile.Gemfile.nokogiri-1.5
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile