matrix:
  include:
    # - rvm: 1.8.7
    #   gemfile: gemfiles/Gemfile.ruby187
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile

script: "bundle exec rake test_with_coveralls"